name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Trigger at midnight UTC every day
  workflow_dispatch: # Manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched to push changes

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install Dependencies
        run: |
          pip install platane-snk  # Install the necessary package

      - name: Generate Snake Animation
        run: |
          python generate_snake.py  # Run your script

      - name: Commit SVG file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required to push changes
